import type { InventoryLocation } from "@/lib/advertising/inventory";

/** Preview inventory. Values mirror the reference process; replace with
 *  Supabase queries in a later phase. */
export const mockLocations: InventoryLocation[] = [
  {
    id: "loc-1",
    type: "standard_audio",
    name: "Oldtown Scottsdale Audio Player #1",
    locationCode: "LOC-8QKD2M4A",
    address: "Old Town, Scottsdale, AZ 85251",
    status: "active",
    monthlyRate: 0,
    dailyTraffic: 0,
    monthlyImpressions: 0,
    linkedDevice: null,
  },
  {
    id: "loc-2",
    type: "standard_audio",
    name: "Mini PC Channel Cast Home HQ",
    locationCode: "LOC-MLZVW52R",
    address: "3605 W. Harrison St., Chandler, AZ 85226",
    status: "available",
    monthlyRate: 100,
    dailyTraffic: 25000,
    monthlyImpressions: 64800000,
    linkedDevice: "Mini PC Channel Cast Home HQ",
  },
  {
    id: "loc-3",
    type: "vision",
    name: "Harbor Lights Resort Lobby",
    locationCode: "LOC-VN7HB3K1",
    address: "1200 Marina Way, San Diego, CA 92101",
    status: "active",
    monthlyRate: 1450,
    dailyTraffic: 8200,
    monthlyImpressions: 4920000,
    linkedDevice: "Harbor Lobby Vision Pod",
  },
  {
    id: "loc-4",
    type: "motion",
    name: "Copper Mesa Pool Deck",
    locationCode: "LOC-MT9PD4X2",
    address: "455 E. Alameda Dr., Tempe, AZ 85282",
    status: "booked",
    monthlyRate: 620,
    dailyTraffic: 1800,
    monthlyImpressions: 1080000,
    linkedDevice: "Pool Deck Motion Player",
  },
  {
    id: "loc-5",
    type: "digital_display",
    name: "Mill Ave Storefront Screen",
    locationCode: "LOC-DD3MLA88",
    address: "680 S. Mill Ave., Tempe, AZ 85281",
    status: "available",
    monthlyRate: 2200,
    dailyTraffic: 31000,
    monthlyImpressions: 9300000,
    linkedDevice: "Mill Ave Screen 01",
  },
  {
    id: "loc-6",
    type: "street_furniture",
    name: "Central Station Transit Bench",
    locationCode: "LOC-SF6TB2QW",
    address: "300 N. Central Ave., Phoenix, AZ 85004",
    status: "available",
    monthlyRate: 900,
    dailyTraffic: 14500,
    monthlyImpressions: 4350000,
    linkedDevice: null,
  },
  {
    id: "loc-7",
    type: "wall_space",
    name: "Roosevelt Row Mural Wall",
    locationCode: "LOC-WS1RRM09",
    address: "912 N. 5th St., Phoenix, AZ 85004",
    status: "maintenance",
    monthlyRate: 1800,
    dailyTraffic: 9800,
    monthlyImpressions: 2940000,
    linkedDevice: null,
  },
];
