import type { DeviceRecord } from "@/lib/devices/devices";

/** Preview device fleet. Replace with Supabase queries in a later phase. */
export const mockDevices: DeviceRecord[] = [
  {
    id: "dev-1",
    deviceCode: "CC-SA-9QK4",
    name: "Mini PC Channel Cast Home HQ",
    type: "standard_audio",
    model: "Mini PC",
    status: "online",
    provisioningMode: "field_install",
    ownerOrg: "Channel Cast",
    locationName: "Mini PC Channel Cast Home HQ",
    claimCode: null,
    claimExpiresLabel: null,
    firmwareVersion: "0.4.1",
    lastHeartbeat: "12s ago",
    volume: 80,
  },
  {
    id: "dev-2",
    deviceCode: "CC-AV-3MHB",
    name: "Harbor Lobby Vision Pod",
    type: "ai_vision",
    model: "Channel Cast AI Vision Node",
    status: "warning",
    provisioningMode: "field_install",
    ownerOrg: "Harbor Lights Resort",
    locationName: "Harbor Lights Resort Lobby",
    claimCode: null,
    claimExpiresLabel: null,
    firmwareVersion: "0.4.0",
    lastHeartbeat: "3m ago",
    volume: 65,
  },
  {
    id: "dev-3",
    deviceCode: "CC-MO-8PD4",
    name: "Pool Deck Motion Player",
    type: "pir_motion",
    model: "Raspberry Pi 4",
    status: "offline",
    provisioningMode: "field_install",
    ownerOrg: "Copper Mesa Apartments",
    locationName: "Copper Mesa Pool Deck",
    claimCode: null,
    claimExpiresLabel: null,
    firmwareVersion: "0.3.8",
    lastHeartbeat: "2h ago",
    volume: 70,
  },
  {
    id: "dev-4",
    deviceCode: "CC-SA-2XVW",
    name: "Oldtown Scottsdale Audio Player #1",
    type: "standard_audio",
    model: "Mini PC",
    status: "registered",
    provisioningMode: "self_service",
    ownerOrg: "Oldtown Merchants",
    locationName: "Oldtown Scottsdale Audio Player #1",
    claimCode: "WXYZ-4821",
    claimExpiresLabel: "in 6 days",
    firmwareVersion: null,
    lastHeartbeat: null,
    volume: 80,
  },
  {
    id: "dev-5",
    deviceCode: "CC-DD-5MLA",
    name: "Mill Ave Screen 01",
    type: "digital_display",
    model: "BrightSign Player",
    status: "needs_setup",
    provisioningMode: "field_install",
    ownerOrg: "Channel Cast",
    locationName: "Mill Ave Storefront Screen",
    claimCode: "K7PN-3Q22",
    claimExpiresLabel: "in 7 days",
    firmwareVersion: null,
    lastHeartbeat: null,
    volume: 100,
  },
];
